	
var BusinessConstants = {
	BUSINESSES_RECEIVED: "BUSINESSES_RECEIVED",
	BUSINESS_RECEIVED: "BUSINESS_RECEIVED",
	SINGLE_BUSINESS_RECEIVED: "SINGLE_BUSINESS_RECEIVED",
	MATCHES_RECEIVED: "MATCHES_RECEIVED",
	REVIEW_RECEIVED: "REVIEW_RECEIVED",
	PHOTO_RECIEVED: "PHOTO_RECIEVED",
	ERROR: "ERROR"
};

module.exports = BusinessConstants;