
var BusinessConstants = {
	BUSINESSES_RECEIVED: "BUSINESSES_RECEIVED",
	BUSINESS_RECEIVED: "BUSINESS_RECEIVED",
	MATCHES_RECEIVED: "MATCHES_RECEIVED",
	REVIEW_RECEIVED: "REVIEW_RECEIVED"
};

module.exports = BusinessConstants;